### ISSUE TITLE
Classloader can't find my own classes

### ISSUE THREAD

**Issue by alexanderkjall** [kwon37xi/hibernate4-memcached#20]
Hi

I upgraded my play framework application to use hibernate 4.2.15 and switched from the com.googlecode.xmemcached cache project to this one.

When I'm doing a query I get a ClassNotFoundException inside your code.

It's pretty hard to find out if it's hibernate that creates a classloader that doesn't see my classes, or if it's play, or if it's your code that does it somehow. So this might not be an issue in this project.

I'm attaching the stacktrace that I get when I try to do a JPA.em().createNamedQuery(namedQuery).getResultList().

    play.exceptions.JavaExecutionException: models.common.retailer.RetailerTransportPoint class is not found.
            at play.mvc.ActionInvoker.invoke(ActionInvoker.java:228)
            at Invocation.HTTP Request(Play!)
        Caused by: java.lang.IllegalArgumentException: models.common.retailer.RetailerTransportPoint class is not found.
            at kr.pe.kwonnam.hibernate4memcached.regions.CacheItem.getSubclassName(CacheItem.java:83)
            at kr.pe.kwonnam.hibernate4memcached.regions.CacheItem.parseTargetClass(CacheItem.java:57)
            at kr.pe.kwonnam.hibernate4memcached.regions.CacheItem.<init>(CacheItem.java:53)
            at kr.pe.kwonnam.hibernate4memcached.regions.GeneralDataMemcachedRegion.put(GeneralDataMemcachedRegion.java:80)
            at kr.pe.kwonnam.hibernate4memcached.strategies.MemcachedRegionAccessStrategy.putFromLoad(MemcachedRegionAccessStrategy.java:52)
            at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:219)
            at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:137)
            at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1112)
            at org.hibernate.loader.Loader.processResultSet(Loader.java:969)
            at org.hibernate.loader.Loader.doQuery(Loader.java:917)
            at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:348)
            at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:318)
            at org.hibernate.loader.Loader.loadEntity(Loader.java:2145)
            at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82)
            at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72)
            at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3939)
            at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:462)
            at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:431)
            at org.hibernate.event.internal.DefaultLoadEventListener.loadByDerivedIdentitySimplePkValue(DefaultLoadEventListener.java:179)
            at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:124)
            at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1017)
            at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:944)
            at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:714)
            at org.hibernate.type.EntityType.resolve(EntityType.java:502)
            at org.hibernate.engine.internal.TwoPhaseLoad.doInitializeEntity(TwoPhaseLoad.java:168)
            at org.hibernate.engine.internal.TwoPhaseLoad.initializeEntity(TwoPhaseLoad.java:137)
            at org.hibernate.loader.Loader.initializeEntitiesAndCollections(Loader.java:1112)
            at org.hibernate.loader.Loader.processResultSet(Loader.java:969)
            at org.hibernate.loader.Loader.doQuery(Loader.java:917)
            at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:348)
            at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:318)
            at org.hibernate.loader.Loader.loadEntity(Loader.java:2145)
            at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:82)
            at org.hibernate.loader.entity.AbstractEntityLoader.load(AbstractEntityLoader.java:72)
            at org.hibernate.persister.entity.AbstractEntityPersister.load(AbstractEntityPersister.java:3939)
            at org.hibernate.event.internal.DefaultLoadEventListener.loadFromDatasource(DefaultLoadEventListener.java:462)
            at org.hibernate.event.internal.DefaultLoadEventListener.doLoad(DefaultLoadEventListener.java:431)
            at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:208)
            at org.hibernate.event.internal.DefaultLoadEventListener.proxyOrLoad(DefaultLoadEventListener.java:264)
            at org.hibernate.event.internal.DefaultLoadEventListener.onLoad(DefaultLoadEventListener.java:152)
            at org.hibernate.internal.SessionImpl.fireLoad(SessionImpl.java:1017)
            at org.hibernate.internal.SessionImpl.internalLoad(SessionImpl.java:944)
            at org.hibernate.type.EntityType.resolveIdentifier(EntityType.java:714)
            at org.hibernate.type.ManyToOneType.assemble(ManyToOneType.java:282)
            at org.hibernate.cache.internal.StandardQueryCache.get(StandardQueryCache.java:170)
            at org.hibernate.loader.Loader.getResultFromQueryCache(Loader.java:2477)
            at org.hibernate.loader.Loader.listUsingQueryCache(Loader.java:2385)
            at org.hibernate.loader.Loader.list(Loader.java:2358)
            at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:495)
            at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:357)
            at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:198)
            at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1194)
            at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
            at org.hibernate.ejb.QueryImpl.getSingleResult(QueryImpl.java:287)
            at common.util.JPAWrapper.getQueryCachedSingleResultFromNamedQuery(JPAWrapper.java:363)
            at controllers.retailer.Retailers.show(Retailers.java:1297)
            at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:524)
            at play.mvc.ActionInvoker.invoke(ActionInvoker.java:475)
            at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:451)
            at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:446)
            at play.mvc.ActionInvoker.invoke(ActionInvoker.java:160)
            ... 1 more
        Caused by: java.lang.ClassNotFoundException: models.common.retailer.RetailerTransportPoint
            at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
            at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
            at java.security.AccessController.doPrivileged(Native Method)
            at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
            at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
            at java.lang.Class.forName0(Native Method)
            at java.lang.Class.forName(Class.java:190)
            at kr.pe.kwonnam.hibernate4memcached.regions.CacheItem.getSubclassName(CacheItem.java:81)
            ... 61 more

**Comment by kwon37xi** [comment]
I haven't tried play framework, So I don't know exactly about that.
Anyway I think your entity class "RetailerTransportPoint" and hibernate are in different class loaders and hibernate's classloader may not be able to load your entity class.

I had also classloader problems with hibernate/JPA, If you're using persistence.xml please try to specify entity classes with `<class>models.common.retailer.RetailerTransportPoint</class>`.
If it succeeds, you'd better specify all entity class names with `<class>`.

**Comment by kwon37xi** [comment]
No further information
